[project]
name = "voiceos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faster-whisper>=1.2.1",
    "keyboard>=0.13.5",
    "numpy>=2.3.5",
    "sounddevice>=0.5.3",
]
